#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

use Velocityorg\GitlabIssueByMail\Command\FetchMailCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new FetchMailCommand());
$application->run();
